<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TC_A_W1DFP_CommunityView</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d9ae4b9e-78a8-4ce9-ab25-952fae2ceec4</testSuiteGuid>
   <testCaseLink>
      <guid>ff61e462-0638-4bd9-8974-e4f777ada5e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/00.Web/00.Common Test Cases/Test Case - Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ce9a69d-65e7-4ec8-97ce-cd9f0c446b0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5505120-125c-4bb5-a627-e52885793214</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a54f520a-4dd0-4beb-a98c-73152a14617c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c9b72ef8-3dc8-4b24-b482-e8a305348e08</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/00.Web/02.SalesForce/00.Web/TC_A_W1DFP_CommunityView</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
