<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Test Suite - IOS - Testing FSL - GJ006</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>777a7583-5eb5-4a64-92a1-743da6258bc1</testSuiteGuid>
   <testCaseLink>
      <guid>ee20daca-26e2-4bb2-8cf3-67d1bc0ff0e9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/01.Mobile/01.IOS/01.Sales Force/00.Common Test Cases/Test Case(IOS) - Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ee46c0cd-1eb2-4b8c-8d3e-4f5863c4d8aa</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data - IOS/00.W1Day/00.IOS - Login</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>ee46c0cd-1eb2-4b8c-8d3e-4f5863c4d8aa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>startAppPath</value>
         <variableId>29ef43c7-fbab-4cdf-b2c5-ab82e412c0c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ee46c0cd-1eb2-4b8c-8d3e-4f5863c4d8aa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>slctEnvironment</value>
         <variableId>4c890f27-e984-4a91-bb7c-b28bc3f8d05c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ee46c0cd-1eb2-4b8c-8d3e-4f5863c4d8aa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>inptUser</value>
         <variableId>40dd21c9-5a57-4300-9b91-e80ba8d4fd23</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ee46c0cd-1eb2-4b8c-8d3e-4f5863c4d8aa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>inptPassword</value>
         <variableId>fe2e08d3-de01-43fb-b5ba-94576f08dcf0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ee46c0cd-1eb2-4b8c-8d3e-4f5863c4d8aa</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>passCode</value>
         <variableId>5552bd52-c0e2-4945-9518-096ef49dc2cb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
