<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnGO</name>
   <tag></tag>
   <elementGuidId>131bb4e6-17c3-44cb-b56f-f5281acb08f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='edit-submit']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='edit-submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='edit-submit']</value>
   </webElementProperties>
</WebElementEntity>
