<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inptCloseDate</name>
   <tag></tag>
   <elementGuidId>cc7771c9-f99a-4e2d-bad4-f2f378352262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-81</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='DATE_CloseDate']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'DATE_CloseDate')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='DATE_CloseDate']</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-81']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content_5:847;a']/article/div/div[2]/div/div/flowruntime-flow-screen-input/flowruntime-input-wrapper2/div/lightning-input/lightning-datepicker/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-datepicker/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
