<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtAppointmentBooked</name>
   <tag></tag>
   <elementGuidId>e5143b98-29e7-44bd-98a6-19cf25bcfa71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='ResultTextLine']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ResultTextLine']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='ResultTextLine']</value>
   </webElementProperties>
</WebElementEntity>
