<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputAddress-LeadSC</name>
   <tag></tag>
   <elementGuidId>c26a54c3-b05d-4f05-9332-44094ef8a8e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-3354']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='input-3354']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='input-3354']</value>
   </webElementProperties>
</WebElementEntity>
