<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtboxZipcodeResidentialLead</name>
   <tag></tag>
   <elementGuidId>129f02a2-efa1-42e8-9e01-8c6b87faa0fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='TXT_Zip_Code_Residential']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='TXT_Zip_Code_Residential']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='TXT_Zip_Code_Residential']</value>
   </webElementProperties>
</WebElementEntity>
