<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slctWorkType</name>
   <tag></tag>
   <elementGuidId>2f422799-d21d-473b-a5a7-98eda1a55bf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AN-ServiceTypeInput']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='AN-ServiceTypeInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='AN-ServiceTypeInput']</value>
   </webElementProperties>
</WebElementEntity>
