<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnConvertLead</name>
   <tag></tag>
   <elementGuidId>42bc46f8-2ddf-47b7-9c71-1896ca3f7fd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='Lead.Convert_Single_Lead']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@name='Lead.Convert_Single_Lead']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@name='Lead.Convert_Single_Lead']</value>
   </webElementProperties>
</WebElementEntity>
