<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDispatchedStatus</name>
   <tag></tag>
   <elementGuidId>c7caab88-bcda-4414-9781-ff719af7e62c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@status=&quot;Dispatched&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@status=&quot;Dispatched&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@status=&quot;Dispatched&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/01.GJOBE/01.Flows/03.Service Appointment Details/iFrameSAChangeStatus</value>
   </webElementProperties>
</WebElementEntity>
