<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSaveServiceResource</name>
   <tag></tag>
   <elementGuidId>5ba6d1b5-850d-486c-9e89-361592028081</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@title='Save']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@title='Save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@title='Save']</value>
   </webElementProperties>
</WebElementEntity>
