<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iFrameSAChangeStatus</name>
   <tag></tag>
   <elementGuidId>9ff86590-f3cc-4f48-a6f6-ce5e561f938c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@id='ServiceAppointment.FSL__Change_Status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//iframe[@id='ServiceAppointment.FSL__Change_Status']</value>
   </webElementProperties>
</WebElementEntity>
