<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtboxSearchServiceAppointment</name>
   <tag></tag>
   <elementGuidId>e33ceeac-9eef-4893-ae38-9aafd3be0e0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@name='ServiceAppointment-search-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@name='ServiceAppointment-search-input']</value>
   </webElementProperties>
</WebElementEntity>
